// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package analytics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AnalyticsClient is the client API for Analytics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsClient interface {
	// GetTodayRevenue сколько заработал топ-менеджмент за сегодня
	GetTodayRevenue(ctx context.Context, in *GetTodayRevenueRequest, opts ...grpc.CallOption) (*GetTodayRevenueResponse, error)
	// GetUnprofitableCount сколько попугов вышло в минус за сегодня
	GetUnprofitableCount(ctx context.Context, in *GetUnprofitableCountRequest, opts ...grpc.CallOption) (*GetUnprofitableCountResponse, error)
	// GetMostExpensiveTask самая дорогая задача за промежуток времени
	GetMostExpensiveTask(ctx context.Context, in *GetMostExpensiveTaskRequest, opts ...grpc.CallOption) (*GetMostExpensiveTaskResponse, error)
}

type analyticsClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsClient(cc grpc.ClientConnInterface) AnalyticsClient {
	return &analyticsClient{cc}
}

func (c *analyticsClient) GetTodayRevenue(ctx context.Context, in *GetTodayRevenueRequest, opts ...grpc.CallOption) (*GetTodayRevenueResponse, error) {
	out := new(GetTodayRevenueResponse)
	err := c.cc.Invoke(ctx, "/Analytics/GetTodayRevenue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsClient) GetUnprofitableCount(ctx context.Context, in *GetUnprofitableCountRequest, opts ...grpc.CallOption) (*GetUnprofitableCountResponse, error) {
	out := new(GetUnprofitableCountResponse)
	err := c.cc.Invoke(ctx, "/Analytics/GetUnprofitableCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsClient) GetMostExpensiveTask(ctx context.Context, in *GetMostExpensiveTaskRequest, opts ...grpc.CallOption) (*GetMostExpensiveTaskResponse, error) {
	out := new(GetMostExpensiveTaskResponse)
	err := c.cc.Invoke(ctx, "/Analytics/GetMostExpensiveTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServer is the server API for Analytics service.
// All implementations must embed UnimplementedAnalyticsServer
// for forward compatibility
type AnalyticsServer interface {
	// GetTodayRevenue сколько заработал топ-менеджмент за сегодня
	GetTodayRevenue(context.Context, *GetTodayRevenueRequest) (*GetTodayRevenueResponse, error)
	// GetUnprofitableCount сколько попугов вышло в минус за сегодня
	GetUnprofitableCount(context.Context, *GetUnprofitableCountRequest) (*GetUnprofitableCountResponse, error)
	// GetMostExpensiveTask самая дорогая задача за промежуток времени
	GetMostExpensiveTask(context.Context, *GetMostExpensiveTaskRequest) (*GetMostExpensiveTaskResponse, error)
	mustEmbedUnimplementedAnalyticsServer()
}

// UnimplementedAnalyticsServer must be embedded to have forward compatible implementations.
type UnimplementedAnalyticsServer struct {
}

func (UnimplementedAnalyticsServer) GetTodayRevenue(context.Context, *GetTodayRevenueRequest) (*GetTodayRevenueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTodayRevenue not implemented")
}
func (UnimplementedAnalyticsServer) GetUnprofitableCount(context.Context, *GetUnprofitableCountRequest) (*GetUnprofitableCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnprofitableCount not implemented")
}
func (UnimplementedAnalyticsServer) GetMostExpensiveTask(context.Context, *GetMostExpensiveTaskRequest) (*GetMostExpensiveTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMostExpensiveTask not implemented")
}
func (UnimplementedAnalyticsServer) mustEmbedUnimplementedAnalyticsServer() {}

// UnsafeAnalyticsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServer will
// result in compilation errors.
type UnsafeAnalyticsServer interface {
	mustEmbedUnimplementedAnalyticsServer()
}

func RegisterAnalyticsServer(s grpc.ServiceRegistrar, srv AnalyticsServer) {
	s.RegisterService(&Analytics_ServiceDesc, srv)
}

func _Analytics_GetTodayRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTodayRevenueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServer).GetTodayRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Analytics/GetTodayRevenue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServer).GetTodayRevenue(ctx, req.(*GetTodayRevenueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analytics_GetUnprofitableCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnprofitableCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServer).GetUnprofitableCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Analytics/GetUnprofitableCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServer).GetUnprofitableCount(ctx, req.(*GetUnprofitableCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analytics_GetMostExpensiveTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMostExpensiveTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServer).GetMostExpensiveTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Analytics/GetMostExpensiveTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServer).GetMostExpensiveTask(ctx, req.(*GetMostExpensiveTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Analytics_ServiceDesc is the grpc.ServiceDesc for Analytics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Analytics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Analytics",
	HandlerType: (*AnalyticsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTodayRevenue",
			Handler:    _Analytics_GetTodayRevenue_Handler,
		},
		{
			MethodName: "GetUnprofitableCount",
			Handler:    _Analytics_GetUnprofitableCount_Handler,
		},
		{
			MethodName: "GetMostExpensiveTask",
			Handler:    _Analytics_GetMostExpensiveTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics/analytics.proto",
}
