// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package analytics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AnalyticsClient is the client API for Analytics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsClient interface {
	// GetTodayRevenue сколько заработал топ-менеджмент за сегодня
	GetTodayEarnings(ctx context.Context, in *GetTodayEarningsRequest, opts ...grpc.CallOption) (*GetTodayEarningsResponse, error)
	// GetUnprofitableCount сколько попугов вышло в минус за сегодня
	GetNonProfitPopugCount(ctx context.Context, in *GetNonProfitPopugCountRequest, opts ...grpc.CallOption) (*GetNonProfitPopugCountResponse, error)
	// GetMostExpensiveTask самая дорогая задача за промежуток времени
	GetMostExpensiveTask(ctx context.Context, in *GetMostExpensiveTaskRequest, opts ...grpc.CallOption) (*GetMostExpensiveTaskResponse, error)
}

type analyticsClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsClient(cc grpc.ClientConnInterface) AnalyticsClient {
	return &analyticsClient{cc}
}

func (c *analyticsClient) GetTodayEarnings(ctx context.Context, in *GetTodayEarningsRequest, opts ...grpc.CallOption) (*GetTodayEarningsResponse, error) {
	out := new(GetTodayEarningsResponse)
	err := c.cc.Invoke(ctx, "/Analytics/GetTodayEarnings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsClient) GetNonProfitPopugCount(ctx context.Context, in *GetNonProfitPopugCountRequest, opts ...grpc.CallOption) (*GetNonProfitPopugCountResponse, error) {
	out := new(GetNonProfitPopugCountResponse)
	err := c.cc.Invoke(ctx, "/Analytics/GetNonProfitPopugCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsClient) GetMostExpensiveTask(ctx context.Context, in *GetMostExpensiveTaskRequest, opts ...grpc.CallOption) (*GetMostExpensiveTaskResponse, error) {
	out := new(GetMostExpensiveTaskResponse)
	err := c.cc.Invoke(ctx, "/Analytics/GetMostExpensiveTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServer is the server API for Analytics service.
// All implementations must embed UnimplementedAnalyticsServer
// for forward compatibility
type AnalyticsServer interface {
	// GetTodayRevenue сколько заработал топ-менеджмент за сегодня
	GetTodayEarnings(context.Context, *GetTodayEarningsRequest) (*GetTodayEarningsResponse, error)
	// GetUnprofitableCount сколько попугов вышло в минус за сегодня
	GetNonProfitPopugCount(context.Context, *GetNonProfitPopugCountRequest) (*GetNonProfitPopugCountResponse, error)
	// GetMostExpensiveTask самая дорогая задача за промежуток времени
	GetMostExpensiveTask(context.Context, *GetMostExpensiveTaskRequest) (*GetMostExpensiveTaskResponse, error)
	mustEmbedUnimplementedAnalyticsServer()
}

// UnimplementedAnalyticsServer must be embedded to have forward compatible implementations.
type UnimplementedAnalyticsServer struct {
}

func (UnimplementedAnalyticsServer) GetTodayEarnings(context.Context, *GetTodayEarningsRequest) (*GetTodayEarningsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTodayEarnings not implemented")
}
func (UnimplementedAnalyticsServer) GetNonProfitPopugCount(context.Context, *GetNonProfitPopugCountRequest) (*GetNonProfitPopugCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNonProfitPopugCount not implemented")
}
func (UnimplementedAnalyticsServer) GetMostExpensiveTask(context.Context, *GetMostExpensiveTaskRequest) (*GetMostExpensiveTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMostExpensiveTask not implemented")
}
func (UnimplementedAnalyticsServer) mustEmbedUnimplementedAnalyticsServer() {}

// UnsafeAnalyticsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServer will
// result in compilation errors.
type UnsafeAnalyticsServer interface {
	mustEmbedUnimplementedAnalyticsServer()
}

func RegisterAnalyticsServer(s grpc.ServiceRegistrar, srv AnalyticsServer) {
	s.RegisterService(&Analytics_ServiceDesc, srv)
}

func _Analytics_GetTodayEarnings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTodayEarningsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServer).GetTodayEarnings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Analytics/GetTodayEarnings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServer).GetTodayEarnings(ctx, req.(*GetTodayEarningsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analytics_GetNonProfitPopugCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNonProfitPopugCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServer).GetNonProfitPopugCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Analytics/GetNonProfitPopugCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServer).GetNonProfitPopugCount(ctx, req.(*GetNonProfitPopugCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analytics_GetMostExpensiveTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMostExpensiveTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServer).GetMostExpensiveTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Analytics/GetMostExpensiveTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServer).GetMostExpensiveTask(ctx, req.(*GetMostExpensiveTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Analytics_ServiceDesc is the grpc.ServiceDesc for Analytics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Analytics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Analytics",
	HandlerType: (*AnalyticsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTodayEarnings",
			Handler:    _Analytics_GetTodayEarnings_Handler,
		},
		{
			MethodName: "GetNonProfitPopugCount",
			Handler:    _Analytics_GetNonProfitPopugCount_Handler,
		},
		{
			MethodName: "GetMostExpensiveTask",
			Handler:    _Analytics_GetMostExpensiveTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics/analytics.proto",
}
